FROM golang:1.22.0-alpine3.19
RUN apk update && apk add bash && apk add curl && apk add nodejs npm
RUN go install -v golang.org/x/tools/gopls@latest && \
    go install -v github.com/cweill/gotests/gotests@v1.6.0 && \
    go install -v github.com/fatih/gomodifytags@v1.16.0 && \
    go install -v github.com/josharian/impl@v1.1.0 && \
    go install -v github.com/haya14busa/goplay/cmd/goplay@v1.0.0 && \
    go install -v github.com/go-delve/delve/cmd/dlv@latest && \
    go install -v honnef.co/go/tools/cmd/staticcheck@latest
RUN adduser --uid 1000 --disabled-password appuser
#USER appuser
WORKDIR /app
CMD ["tail", "-f", "/dev/null"]

